framework: mocha
blocklist:
  - regions.spec.js##AWS Regions##should have same regions for AWS, China, and GovCloud##
preRun:
  command:
    - npm install
    - npm run lint
preMerge:
  pattern:
    - "./**/*.spec.js"
postMerge:
  pattern: 
    - "./**/*.spec.js"
postRun:
  command:
    - node --version
version: 1.0
